#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

message="$(cat $1)"
# 提交规范
requiredPattern="^(feat|fix|docs|style|refactor|perf|test|chore|revert|Merge).*$"

if ! [[ $message =~ $requiredPattern ]]; then
  echo "🚨 提交信息不符合规范😕 ！请参考以下规范：
  -
  feat: 新功能（feature）
  fix: 修补 bug
  docs: 仅仅修改了文档，比如 README, CHANGELOG, CONTRIBUTE 等等
  style: 仅仅修改了空格、格式缩进、逗号等等，不改变代码逻辑
  refactor: 代码重构，没有加新功能或者修复 bug
  perf: 优化相关，比如提升性能、体验
  test: 测试用例，包括单元测试、集成测试等
  chore: 改变构建流程、或者增加依赖库、工具等
  revert: 回滚到上一个版本
  -
  "
  exit 1
fi
